sudo: required

language: csharp

mono: none
dotnet: 2.0.0
dist: trusty

env:
    - ELASTIC_BEANSTALK_LABEL=$Version.$TRAVIS_BUILD_NUMBER

script:
    - dotnet restore ./src/Guilded/Guilded.csproj
    - dotnet build ./src/Guilded/Guilded.csproj -c Release
    - dotnet test ./test/Guilded.Tests/Guilded.Tests.csproj

after_success:
    # Download resources
    - cd ./src/Guilded
    - npm install
    - npm run bower install
    - npm run gulp scripts styles
    - mkdir -p ./obj/Docker/publish/wwwroot
    - mv ./wwwroot/lib ./obj/Docker/publish/wwwroot
    # dotnet publish output parameter is relative to project
    - dotnet publish -c Release -o ./obj/Docker/publish
    - rm ./obj/Docker/publish/wwwroot/css/**/*.less
    - rm ./obj/Docker/publish/wwwroot/js/**/*.ts
    # Run docker build for images
    - docker build -t bwolfing/guilded:dev-$Version.$TRAVIS_BUILD_NUMBER .
    - docker build -t bwolfing/guilded:dev-latest .
    # Push to docker hub
    - docker login -u="$DockerLogin" -p="$DockerPassword"
    - docker push bwolfing/guilded:dev-$Version.$TRAVIS_BUILD_NUMBER
    - docker push bwolfing/guilded:dev-latest

before_deploy:
    # Remove all files that are not Dockerrun.aws.json
    - shopt -s extglob
    - rm -rf -- !(Dockerrun.aws.json)

deploy:
    skip_cleanup: true
    provider: elasticbeanstalk
    access-key-id: $AwsAccessKey
    secret-access-key: 
        secure: $AwsSecretKey
    region: us-west-1
    app: Guilded
    env: Guilded-dev
    bucket_name: elasticbeanstalk-us-west-1-126711177368
